/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MeuHistoricoRouteImport } from './routes/meu-historico'
import { Route as LoginQrRouteImport } from './routes/login-qr'
import { Route as JoinRouteImport } from './routes/join'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RemoteIndexRouteImport } from './routes/remote.index'
import { Route as RemoteIdRouteImport } from './routes/remote.$id'
import { Route as RemoteSetupIdRouteImport } from './routes/remote-setup.$id'
import { Route as QuizNewRouteImport } from './routes/quiz.new'
import { Route as QrAuthTokenRouteImport } from './routes/qr-auth.$token'
import { Route as PresentIdRouteImport } from './routes/present.$id'
import { Route as OperatorIdRouteImport } from './routes/operator.$id'
import { Route as LobbyIdRouteImport } from './routes/lobby.$id'
import { Route as EventNewRouteImport } from './routes/event.new'
import { Route as EventIdRouteImport } from './routes/event.$id'
import { Route as RemoteIdJoinRouteImport } from './routes/remote.$id.join'
import { Route as QuizIdEditRouteImport } from './routes/quiz.$id.edit'
import { Route as PresentIdReviewRouteImport } from './routes/present.$id.review'
import { Route as PresentIdPairRouteImport } from './routes/present.$id.pair'
import { Route as EventIdPodiumRouteImport } from './routes/event.$id.podium'
import { Route as EventIdClassificacaoGeralRouteImport } from './routes/event.$id.classificacao-geral'

const MeuHistoricoRoute = MeuHistoricoRouteImport.update({
  id: '/meu-historico',
  path: '/meu-historico',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginQrRoute = LoginQrRouteImport.update({
  id: '/login-qr',
  path: '/login-qr',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RemoteIndexRoute = RemoteIndexRouteImport.update({
  id: '/remote/',
  path: '/remote/',
  getParentRoute: () => rootRouteImport,
} as any)
const RemoteIdRoute = RemoteIdRouteImport.update({
  id: '/remote/$id',
  path: '/remote/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RemoteSetupIdRoute = RemoteSetupIdRouteImport.update({
  id: '/remote-setup/$id',
  path: '/remote-setup/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizNewRoute = QuizNewRouteImport.update({
  id: '/quiz/new',
  path: '/quiz/new',
  getParentRoute: () => rootRouteImport,
} as any)
const QrAuthTokenRoute = QrAuthTokenRouteImport.update({
  id: '/qr-auth/$token',
  path: '/qr-auth/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const PresentIdRoute = PresentIdRouteImport.update({
  id: '/present/$id',
  path: '/present/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const OperatorIdRoute = OperatorIdRouteImport.update({
  id: '/operator/$id',
  path: '/operator/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const LobbyIdRoute = LobbyIdRouteImport.update({
  id: '/lobby/$id',
  path: '/lobby/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const EventNewRoute = EventNewRouteImport.update({
  id: '/event/new',
  path: '/event/new',
  getParentRoute: () => rootRouteImport,
} as any)
const EventIdRoute = EventIdRouteImport.update({
  id: '/event/$id',
  path: '/event/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RemoteIdJoinRoute = RemoteIdJoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => RemoteIdRoute,
} as any)
const QuizIdEditRoute = QuizIdEditRouteImport.update({
  id: '/quiz/$id/edit',
  path: '/quiz/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const PresentIdReviewRoute = PresentIdReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => PresentIdRoute,
} as any)
const PresentIdPairRoute = PresentIdPairRouteImport.update({
  id: '/pair',
  path: '/pair',
  getParentRoute: () => PresentIdRoute,
} as any)
const EventIdPodiumRoute = EventIdPodiumRouteImport.update({
  id: '/podium',
  path: '/podium',
  getParentRoute: () => EventIdRoute,
} as any)
const EventIdClassificacaoGeralRoute =
  EventIdClassificacaoGeralRouteImport.update({
    id: '/classificacao-geral',
    path: '/classificacao-geral',
    getParentRoute: () => EventIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/join': typeof JoinRoute
  '/login-qr': typeof LoginQrRoute
  '/meu-historico': typeof MeuHistoricoRoute
  '/event/$id': typeof EventIdRouteWithChildren
  '/event/new': typeof EventNewRoute
  '/lobby/$id': typeof LobbyIdRoute
  '/operator/$id': typeof OperatorIdRoute
  '/present/$id': typeof PresentIdRouteWithChildren
  '/qr-auth/$token': typeof QrAuthTokenRoute
  '/quiz/new': typeof QuizNewRoute
  '/remote-setup/$id': typeof RemoteSetupIdRoute
  '/remote/$id': typeof RemoteIdRouteWithChildren
  '/remote/': typeof RemoteIndexRoute
  '/event/$id/classificacao-geral': typeof EventIdClassificacaoGeralRoute
  '/event/$id/podium': typeof EventIdPodiumRoute
  '/present/$id/pair': typeof PresentIdPairRoute
  '/present/$id/review': typeof PresentIdReviewRoute
  '/quiz/$id/edit': typeof QuizIdEditRoute
  '/remote/$id/join': typeof RemoteIdJoinRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/join': typeof JoinRoute
  '/login-qr': typeof LoginQrRoute
  '/meu-historico': typeof MeuHistoricoRoute
  '/event/$id': typeof EventIdRouteWithChildren
  '/event/new': typeof EventNewRoute
  '/lobby/$id': typeof LobbyIdRoute
  '/operator/$id': typeof OperatorIdRoute
  '/present/$id': typeof PresentIdRouteWithChildren
  '/qr-auth/$token': typeof QrAuthTokenRoute
  '/quiz/new': typeof QuizNewRoute
  '/remote-setup/$id': typeof RemoteSetupIdRoute
  '/remote/$id': typeof RemoteIdRouteWithChildren
  '/remote': typeof RemoteIndexRoute
  '/event/$id/classificacao-geral': typeof EventIdClassificacaoGeralRoute
  '/event/$id/podium': typeof EventIdPodiumRoute
  '/present/$id/pair': typeof PresentIdPairRoute
  '/present/$id/review': typeof PresentIdReviewRoute
  '/quiz/$id/edit': typeof QuizIdEditRoute
  '/remote/$id/join': typeof RemoteIdJoinRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/join': typeof JoinRoute
  '/login-qr': typeof LoginQrRoute
  '/meu-historico': typeof MeuHistoricoRoute
  '/event/$id': typeof EventIdRouteWithChildren
  '/event/new': typeof EventNewRoute
  '/lobby/$id': typeof LobbyIdRoute
  '/operator/$id': typeof OperatorIdRoute
  '/present/$id': typeof PresentIdRouteWithChildren
  '/qr-auth/$token': typeof QrAuthTokenRoute
  '/quiz/new': typeof QuizNewRoute
  '/remote-setup/$id': typeof RemoteSetupIdRoute
  '/remote/$id': typeof RemoteIdRouteWithChildren
  '/remote/': typeof RemoteIndexRoute
  '/event/$id/classificacao-geral': typeof EventIdClassificacaoGeralRoute
  '/event/$id/podium': typeof EventIdPodiumRoute
  '/present/$id/pair': typeof PresentIdPairRoute
  '/present/$id/review': typeof PresentIdReviewRoute
  '/quiz/$id/edit': typeof QuizIdEditRoute
  '/remote/$id/join': typeof RemoteIdJoinRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/join'
    | '/login-qr'
    | '/meu-historico'
    | '/event/$id'
    | '/event/new'
    | '/lobby/$id'
    | '/operator/$id'
    | '/present/$id'
    | '/qr-auth/$token'
    | '/quiz/new'
    | '/remote-setup/$id'
    | '/remote/$id'
    | '/remote/'
    | '/event/$id/classificacao-geral'
    | '/event/$id/podium'
    | '/present/$id/pair'
    | '/present/$id/review'
    | '/quiz/$id/edit'
    | '/remote/$id/join'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/join'
    | '/login-qr'
    | '/meu-historico'
    | '/event/$id'
    | '/event/new'
    | '/lobby/$id'
    | '/operator/$id'
    | '/present/$id'
    | '/qr-auth/$token'
    | '/quiz/new'
    | '/remote-setup/$id'
    | '/remote/$id'
    | '/remote'
    | '/event/$id/classificacao-geral'
    | '/event/$id/podium'
    | '/present/$id/pair'
    | '/present/$id/review'
    | '/quiz/$id/edit'
    | '/remote/$id/join'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/join'
    | '/login-qr'
    | '/meu-historico'
    | '/event/$id'
    | '/event/new'
    | '/lobby/$id'
    | '/operator/$id'
    | '/present/$id'
    | '/qr-auth/$token'
    | '/quiz/new'
    | '/remote-setup/$id'
    | '/remote/$id'
    | '/remote/'
    | '/event/$id/classificacao-geral'
    | '/event/$id/podium'
    | '/present/$id/pair'
    | '/present/$id/review'
    | '/quiz/$id/edit'
    | '/remote/$id/join'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  JoinRoute: typeof JoinRoute
  LoginQrRoute: typeof LoginQrRoute
  MeuHistoricoRoute: typeof MeuHistoricoRoute
  EventIdRoute: typeof EventIdRouteWithChildren
  EventNewRoute: typeof EventNewRoute
  LobbyIdRoute: typeof LobbyIdRoute
  OperatorIdRoute: typeof OperatorIdRoute
  PresentIdRoute: typeof PresentIdRouteWithChildren
  QrAuthTokenRoute: typeof QrAuthTokenRoute
  QuizNewRoute: typeof QuizNewRoute
  RemoteSetupIdRoute: typeof RemoteSetupIdRoute
  RemoteIdRoute: typeof RemoteIdRouteWithChildren
  RemoteIndexRoute: typeof RemoteIndexRoute
  QuizIdEditRoute: typeof QuizIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/meu-historico': {
      id: '/meu-historico'
      path: '/meu-historico'
      fullPath: '/meu-historico'
      preLoaderRoute: typeof MeuHistoricoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login-qr': {
      id: '/login-qr'
      path: '/login-qr'
      fullPath: '/login-qr'
      preLoaderRoute: typeof LoginQrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/remote/': {
      id: '/remote/'
      path: '/remote'
      fullPath: '/remote/'
      preLoaderRoute: typeof RemoteIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/remote/$id': {
      id: '/remote/$id'
      path: '/remote/$id'
      fullPath: '/remote/$id'
      preLoaderRoute: typeof RemoteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/remote-setup/$id': {
      id: '/remote-setup/$id'
      path: '/remote-setup/$id'
      fullPath: '/remote-setup/$id'
      preLoaderRoute: typeof RemoteSetupIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz/new': {
      id: '/quiz/new'
      path: '/quiz/new'
      fullPath: '/quiz/new'
      preLoaderRoute: typeof QuizNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qr-auth/$token': {
      id: '/qr-auth/$token'
      path: '/qr-auth/$token'
      fullPath: '/qr-auth/$token'
      preLoaderRoute: typeof QrAuthTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/present/$id': {
      id: '/present/$id'
      path: '/present/$id'
      fullPath: '/present/$id'
      preLoaderRoute: typeof PresentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operator/$id': {
      id: '/operator/$id'
      path: '/operator/$id'
      fullPath: '/operator/$id'
      preLoaderRoute: typeof OperatorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lobby/$id': {
      id: '/lobby/$id'
      path: '/lobby/$id'
      fullPath: '/lobby/$id'
      preLoaderRoute: typeof LobbyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/event/new': {
      id: '/event/new'
      path: '/event/new'
      fullPath: '/event/new'
      preLoaderRoute: typeof EventNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/event/$id': {
      id: '/event/$id'
      path: '/event/$id'
      fullPath: '/event/$id'
      preLoaderRoute: typeof EventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/remote/$id/join': {
      id: '/remote/$id/join'
      path: '/join'
      fullPath: '/remote/$id/join'
      preLoaderRoute: typeof RemoteIdJoinRouteImport
      parentRoute: typeof RemoteIdRoute
    }
    '/quiz/$id/edit': {
      id: '/quiz/$id/edit'
      path: '/quiz/$id/edit'
      fullPath: '/quiz/$id/edit'
      preLoaderRoute: typeof QuizIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/present/$id/review': {
      id: '/present/$id/review'
      path: '/review'
      fullPath: '/present/$id/review'
      preLoaderRoute: typeof PresentIdReviewRouteImport
      parentRoute: typeof PresentIdRoute
    }
    '/present/$id/pair': {
      id: '/present/$id/pair'
      path: '/pair'
      fullPath: '/present/$id/pair'
      preLoaderRoute: typeof PresentIdPairRouteImport
      parentRoute: typeof PresentIdRoute
    }
    '/event/$id/podium': {
      id: '/event/$id/podium'
      path: '/podium'
      fullPath: '/event/$id/podium'
      preLoaderRoute: typeof EventIdPodiumRouteImport
      parentRoute: typeof EventIdRoute
    }
    '/event/$id/classificacao-geral': {
      id: '/event/$id/classificacao-geral'
      path: '/classificacao-geral'
      fullPath: '/event/$id/classificacao-geral'
      preLoaderRoute: typeof EventIdClassificacaoGeralRouteImport
      parentRoute: typeof EventIdRoute
    }
  }
}

interface EventIdRouteChildren {
  EventIdClassificacaoGeralRoute: typeof EventIdClassificacaoGeralRoute
  EventIdPodiumRoute: typeof EventIdPodiumRoute
}

const EventIdRouteChildren: EventIdRouteChildren = {
  EventIdClassificacaoGeralRoute: EventIdClassificacaoGeralRoute,
  EventIdPodiumRoute: EventIdPodiumRoute,
}

const EventIdRouteWithChildren =
  EventIdRoute._addFileChildren(EventIdRouteChildren)

interface PresentIdRouteChildren {
  PresentIdPairRoute: typeof PresentIdPairRoute
  PresentIdReviewRoute: typeof PresentIdReviewRoute
}

const PresentIdRouteChildren: PresentIdRouteChildren = {
  PresentIdPairRoute: PresentIdPairRoute,
  PresentIdReviewRoute: PresentIdReviewRoute,
}

const PresentIdRouteWithChildren = PresentIdRoute._addFileChildren(
  PresentIdRouteChildren,
)

interface RemoteIdRouteChildren {
  RemoteIdJoinRoute: typeof RemoteIdJoinRoute
}

const RemoteIdRouteChildren: RemoteIdRouteChildren = {
  RemoteIdJoinRoute: RemoteIdJoinRoute,
}

const RemoteIdRouteWithChildren = RemoteIdRoute._addFileChildren(
  RemoteIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  JoinRoute: JoinRoute,
  LoginQrRoute: LoginQrRoute,
  MeuHistoricoRoute: MeuHistoricoRoute,
  EventIdRoute: EventIdRouteWithChildren,
  EventNewRoute: EventNewRoute,
  LobbyIdRoute: LobbyIdRoute,
  OperatorIdRoute: OperatorIdRoute,
  PresentIdRoute: PresentIdRouteWithChildren,
  QrAuthTokenRoute: QrAuthTokenRoute,
  QuizNewRoute: QuizNewRoute,
  RemoteSetupIdRoute: RemoteSetupIdRoute,
  RemoteIdRoute: RemoteIdRouteWithChildren,
  RemoteIndexRoute: RemoteIndexRoute,
  QuizIdEditRoute: QuizIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
