/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as JoinRouteImport } from './routes/join'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as QuizNewRouteImport } from './routes/quiz.new'
import { Route as PresentIdRouteImport } from './routes/present.$id'
import { Route as LobbyIdRouteImport } from './routes/lobby.$id'
import { Route as EventNewRouteImport } from './routes/event.new'
import { Route as EventIdIndexRouteImport } from './routes/event.$id.index'
import { Route as QuizIdEditRouteImport } from './routes/quiz.$id.edit'
import { Route as PresentIdReviewRouteImport } from './routes/present.$id.review'
import { Route as EventIdPodiumRouteImport } from './routes/event.$id.podium'
import { Route as EventIdClassificacaoGeralRouteImport } from './routes/event.$id.classificacao-geral'

const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizNewRoute = QuizNewRouteImport.update({
  id: '/quiz/new',
  path: '/quiz/new',
  getParentRoute: () => rootRouteImport,
} as any)
const PresentIdRoute = PresentIdRouteImport.update({
  id: '/present/$id',
  path: '/present/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const LobbyIdRoute = LobbyIdRouteImport.update({
  id: '/lobby/$id',
  path: '/lobby/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const EventNewRoute = EventNewRouteImport.update({
  id: '/event/new',
  path: '/event/new',
  getParentRoute: () => rootRouteImport,
} as any)
const EventIdIndexRoute = EventIdIndexRouteImport.update({
  id: '/event/$id/',
  path: '/event/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizIdEditRoute = QuizIdEditRouteImport.update({
  id: '/quiz/$id/edit',
  path: '/quiz/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const PresentIdReviewRoute = PresentIdReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => PresentIdRoute,
} as any)
const EventIdPodiumRoute = EventIdPodiumRouteImport.update({
  id: '/event/$id/podium',
  path: '/event/$id/podium',
  getParentRoute: () => rootRouteImport,
} as any)
const EventIdClassificacaoGeralRoute =
  EventIdClassificacaoGeralRouteImport.update({
    id: '/event/$id/classificacao-geral',
    path: '/event/$id/classificacao-geral',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/join': typeof JoinRoute
  '/event/new': typeof EventNewRoute
  '/lobby/$id': typeof LobbyIdRoute
  '/present/$id': typeof PresentIdRouteWithChildren
  '/quiz/new': typeof QuizNewRoute
  '/event/$id/classificacao-geral': typeof EventIdClassificacaoGeralRoute
  '/event/$id/podium': typeof EventIdPodiumRoute
  '/present/$id/review': typeof PresentIdReviewRoute
  '/quiz/$id/edit': typeof QuizIdEditRoute
  '/event/$id/': typeof EventIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/join': typeof JoinRoute
  '/event/new': typeof EventNewRoute
  '/lobby/$id': typeof LobbyIdRoute
  '/present/$id': typeof PresentIdRouteWithChildren
  '/quiz/new': typeof QuizNewRoute
  '/event/$id/classificacao-geral': typeof EventIdClassificacaoGeralRoute
  '/event/$id/podium': typeof EventIdPodiumRoute
  '/present/$id/review': typeof PresentIdReviewRoute
  '/quiz/$id/edit': typeof QuizIdEditRoute
  '/event/$id': typeof EventIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/join': typeof JoinRoute
  '/event/new': typeof EventNewRoute
  '/lobby/$id': typeof LobbyIdRoute
  '/present/$id': typeof PresentIdRouteWithChildren
  '/quiz/new': typeof QuizNewRoute
  '/event/$id/classificacao-geral': typeof EventIdClassificacaoGeralRoute
  '/event/$id/podium': typeof EventIdPodiumRoute
  '/present/$id/review': typeof PresentIdReviewRoute
  '/quiz/$id/edit': typeof QuizIdEditRoute
  '/event/$id/': typeof EventIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/join'
    | '/event/new'
    | '/lobby/$id'
    | '/present/$id'
    | '/quiz/new'
    | '/event/$id/classificacao-geral'
    | '/event/$id/podium'
    | '/present/$id/review'
    | '/quiz/$id/edit'
    | '/event/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/join'
    | '/event/new'
    | '/lobby/$id'
    | '/present/$id'
    | '/quiz/new'
    | '/event/$id/classificacao-geral'
    | '/event/$id/podium'
    | '/present/$id/review'
    | '/quiz/$id/edit'
    | '/event/$id'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/join'
    | '/event/new'
    | '/lobby/$id'
    | '/present/$id'
    | '/quiz/new'
    | '/event/$id/classificacao-geral'
    | '/event/$id/podium'
    | '/present/$id/review'
    | '/quiz/$id/edit'
    | '/event/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  JoinRoute: typeof JoinRoute
  EventNewRoute: typeof EventNewRoute
  LobbyIdRoute: typeof LobbyIdRoute
  PresentIdRoute: typeof PresentIdRouteWithChildren
  QuizNewRoute: typeof QuizNewRoute
  EventIdClassificacaoGeralRoute: typeof EventIdClassificacaoGeralRoute
  EventIdPodiumRoute: typeof EventIdPodiumRoute
  QuizIdEditRoute: typeof QuizIdEditRoute
  EventIdIndexRoute: typeof EventIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz/new': {
      id: '/quiz/new'
      path: '/quiz/new'
      fullPath: '/quiz/new'
      preLoaderRoute: typeof QuizNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/present/$id': {
      id: '/present/$id'
      path: '/present/$id'
      fullPath: '/present/$id'
      preLoaderRoute: typeof PresentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lobby/$id': {
      id: '/lobby/$id'
      path: '/lobby/$id'
      fullPath: '/lobby/$id'
      preLoaderRoute: typeof LobbyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/event/new': {
      id: '/event/new'
      path: '/event/new'
      fullPath: '/event/new'
      preLoaderRoute: typeof EventNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/event/$id/': {
      id: '/event/$id/'
      path: '/event/$id'
      fullPath: '/event/$id/'
      preLoaderRoute: typeof EventIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz/$id/edit': {
      id: '/quiz/$id/edit'
      path: '/quiz/$id/edit'
      fullPath: '/quiz/$id/edit'
      preLoaderRoute: typeof QuizIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/present/$id/review': {
      id: '/present/$id/review'
      path: '/review'
      fullPath: '/present/$id/review'
      preLoaderRoute: typeof PresentIdReviewRouteImport
      parentRoute: typeof PresentIdRoute
    }
    '/event/$id/podium': {
      id: '/event/$id/podium'
      path: '/event/$id/podium'
      fullPath: '/event/$id/podium'
      preLoaderRoute: typeof EventIdPodiumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/event/$id/classificacao-geral': {
      id: '/event/$id/classificacao-geral'
      path: '/event/$id/classificacao-geral'
      fullPath: '/event/$id/classificacao-geral'
      preLoaderRoute: typeof EventIdClassificacaoGeralRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface PresentIdRouteChildren {
  PresentIdReviewRoute: typeof PresentIdReviewRoute
}

const PresentIdRouteChildren: PresentIdRouteChildren = {
  PresentIdReviewRoute: PresentIdReviewRoute,
}

const PresentIdRouteWithChildren = PresentIdRoute._addFileChildren(
  PresentIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  JoinRoute: JoinRoute,
  EventNewRoute: EventNewRoute,
  LobbyIdRoute: LobbyIdRoute,
  PresentIdRoute: PresentIdRouteWithChildren,
  QuizNewRoute: QuizNewRoute,
  EventIdClassificacaoGeralRoute: EventIdClassificacaoGeralRoute,
  EventIdPodiumRoute: EventIdPodiumRoute,
  QuizIdEditRoute: QuizIdEditRoute,
  EventIdIndexRoute: EventIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
